version: '3.3'
services:
  db:
    image: postgres:11.8
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - /var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock
      - db-volume:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  back:
    build: ./back
    command: python manage.py runserver 0.0.0.0:8000
    image: back-image
    container_name: back
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./back:/home/app

  front:
    build: ./front
    environment:
      CHOKIDAR_USEPOLLING: "true"
    image: front-image
    container_name: front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app

volumes:
  db-volume:
