# Generated by Django 3.1.7 on 2021-03-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.JSONField(default=list)),
                ('turn', models.IntegerField(choices=[(1, 'Player 1'), (2, 'Player 2')], default=1)),
                ('player1', models.CharField(max_length=20)),
                ('player2', models.CharField(max_length=20)),
                ('winner', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[(1, 'Playing'), (2, 'Finalized')], default=1)),
            ],
        ),
    ]
