# Generated by Django 3.1.7 on 2021-04-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.JSONField(default=list)),
                ('turn', models.IntegerField(choices=[(1, 'Player 1'), (2, 'Player 2')], default=1)),
                ('player1', models.CharField(max_length=20, null=True)),
                ('player2', models.CharField(max_length=20, null=True)),
                ('winner', models.CharField(max_length=20, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Playing'), (2, 'Finalized')], default=0)),
                ('moves', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=7)),
                ('type_game', models.IntegerField(choices=[(1, 'PVP'), (2, 'PVE')], default=1)),
                ('posible_moves', models.JSONField(default=list)),
            ],
        ),
    ]
