# Generated by Django 3.1.7 on 2021-03-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Playing'), (2, 'Finalized')], default=1),
        ),
    ]
