# Generated by Django 3.1.7 on 2021-03-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210325_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
