# Generated by Django 3.1.7 on 2021-03-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210326_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='moves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='size',
            field=models.IntegerField(default=7),
        ),
    ]
